### ISSUE TITLE
IVF / ios_avf_pull fails to start on devices that have dash in UDID

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf_ios_support#59] opened 2020-08-13 07:35 UTC
![image](https://user-images.githubusercontent.com/12910117/90106710-65175d00-dd7a-11ea-85aa-56de728f8593.png)

When i set config video as true.
`{
  "xcode_dev_team_id": "xxxxxxxx",
  "stf": {
    "ip": "10.3.100.155",
    "hostname": "10.3.100.155"
  },
  "video": {
    "enabled": true,
    "use_vnc": false,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 10
  },
  "install": {
    "root_path": "",
    "config_path": "config.json"
  }
}`
It stuck on the ivf process
![image](https://user-images.githubusercontent.com/12910117/90106891-9ee86380-dd7a-11ea-9dcb-fa15914f8803.png)

**Comment by nanoscopic** [comment] 2020-08-13 23:35
Please run `./view_log -proc ivf` from the stf_ios_support folder and respond what the output is. Without some error output I have no way to debug what the issue is that you are encountering.

**Comment by chaooe** [comment] 2020-08-14 01:41
Attached the ivf logs 
2020-08-14 09:39:57.543 ivf_pull[1090:12203] Send data to nanomsg tcp://127.0.0.1:7879


2020-08-14 09:39:58.951 ivf_pull[1093:12354] Send data to nanomsg tcp://127.0.0.1:7879
2020-08-14 09:40:05.057 ivf_pull[1093:12354] device with udid '00008030-0006215134A0802E' not found





2020-08-14 09:40:07.090 ivf_pull[1111:12978] Send data to nanomsg tcp://127.0.0.1:7879
2020-08-14 09:40:13.170 ivf_pull[1111:12978] device with udid '00008030-0006215134A0802E' not found

**Comment by chaooe** [comment] 2020-08-14 01:42
My iPhone is Apple 11, iOS 13.5, with the UUID 00008030-0006215134A0802E

**Comment by nanoscopic** [comment] 2020-08-14 05:03
I believe this is due to the dash in the uuid. I have updated ios_avf_pull to automatically remove the dash: https://github.com/nanoscopic/ios_avf_pull/commit/688a86aa1ca6da79bb7da04bcca62d754a484063

I have also added a 'list' command to the binary. You can run it by pulling the update, rebuilding, and running `./bin/ivf_pull list` from stf_ios_support folder or `./ivf_pull list` from the stf_ios_support/repos/ios_afv_pull directory.

**Comment by chaooe** [comment] 2020-08-14 06:52
I have rebuild it . I can't see the device as below
![图片](https://user-images.githubusercontent.com/12910117/90221897-9b69e080-de3d-11ea-967f-63654477770e.png)

**Comment by chaooe** [comment] 2020-08-14 07:11
I have checked it can get the uuid from previous command idevice_id -l.
alexzhao@apple stf_ios_support_2.git % /usr/local/bin/idevice_id -l
00008030-0006215134A0802E

**Comment by nanoscopic** [comment] 2020-08-14 07:27
What type of IOS device is it? It's possible it is not a "muxed" media type device. That is the only real filter being set while scanning for the device: https://github.com/nanoscopic/ios_avf_pull/blob/master/ivf_pull.m#L286

What IOS version is it running?

Does video appear for your phone if you open quicktime player, start a movie recording, then select your device in the small dropdown next to the record button?

If no video shows in quicktime, then your device is borked somehow. Reboot the phone and try again. If still not working go to settings -> developer -> reset media services on the phone and try again. If it still doesn't work after both those things in quicktime then I have no idea what is wrong with your device.

**Comment by chaooe** [comment] 2020-08-14 08:01
I have two devices. #1 iPhone6s with iOS 13.4.1  #2 iPhone 11 with iOS 13.5.1.
And it seems not working  after i do your steps. it is very strange.

**Comment by nhiendohao** [comment] 2020-08-14 08:50
HI, I'm having the same issue after get the latest version from master. It was working fine before that. ( On my stf browser, I saw connected device, however I could not see the video stream on browser yet)
**iOS version :** 13.5.1
2020-08-14 15:26:51.268 ivf_pull[53799:165899] Send data to nanomsg tcp://127.0.0.1:7879
2020-08-14 15:26:52.359 ivf_pull[53799:165899] device with udid '00008030-0006110134D1802E' not found
**My observation:** I try to use quicktime it does not regconize my phone. Then I try to kill PID of Quicktime then I can view video show on Quicktime again. However, the issue is still there.

**Comment by chaooe** [comment] 2020-08-14 09:09
I am stuck on start the ivf process. After this process it will show the devices on the STF browser. So maybe we faced the same problem.

**Comment by nanoscopic** [comment] 2020-09-20 02:33
In the process of attempting to fix this issue originally I actually broke all devices with a dash in the UDID. In order to ensure maximum compatibility regardless of the behavior of AVFoundation, I've now altered the code to check for both the dash and non-dashed UDID: https://github.com/DeviceFarmer/ios_avf_pull/commit/f61e3780ffecb41e679f684a777f7c856908324e

This should hopefully made it work for all cases and devices. Please comment if not.

**Comment by nanoscopic** [comment] 2020-09-20 03:03
I believe it is fixed now. Feel free to reopen if that is not the case.

**Closed by nanoscopic** 2020-09-20 03:03 UTC
Labels: bug, video

**Comment by chaooe** [comment] 2020-09-23 02:22
no device shown. 
<img width="521" alt="图片" src="https://user-images.githubusercontent.com/12910117/93957241-75155a00-fd86-11ea-9afb-f6b16f5f0155.png">
and use lastest commit f61e3780ffecb41e679f684a777f7c856908324e
<img width="725" alt="图片" src="https://user-images.githubusercontent.com/12910117/93957342-af7ef700-fd86-11ea-9bb5-756029e49913.png">

**Comment by nanoscopic** [comment] 2020-09-24 06:45
Agreed. Last commit was still broken. I have now though made additional changed and actually tested them against an IOS device with a dash in the UDID and it will now work.
